#!/usr/bin/env python3
"""Build a keyword → URL index from Wiki pages and Hugo-generated tag pages.

Inputs:
  - content/wiki/**/*.md  (frontmatter: title, aliases, description)
  - public/tags/*/index.html  (display name + slugified URL, generated by Hugo)
  - hugo.toml  (baseURL → site path prefix)

Output:
  - .claude/temp/keywords.json
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
WIKI_DIR = ROOT / "content" / "wiki"
PUBLIC_DIR = ROOT / "public"
HUGO_TOML = ROOT / "hugo.toml"
OUT_PATH = ROOT / ".claude" / "temp" / "keywords.json"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)\Z", re.DOTALL)
TAG_TITLE_RE = re.compile(r"<h1[^>]*>(.*?)</h1>", re.DOTALL)
HTML_TAG_RE = re.compile(r"<[^>]+>")
ASCII_ONLY_RE = re.compile(r"^[\x00-\x7f]+$")

MIN_ASCII_LEN = 3
MIN_OTHER_LEN = 2


def keyword_passes(kw: str) -> bool:
    kw = kw.strip()
    if not kw:
        return False
    if ASCII_ONLY_RE.match(kw):
        return len(kw) >= MIN_ASCII_LEN
    return len(kw) >= MIN_OTHER_LEN


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        print(f"warn: missing frontmatter: {path.relative_to(ROOT)}", file=sys.stderr)
        return {}
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as exc:
        print(
            f"warn: invalid frontmatter: {path.relative_to(ROOT)}: {exc}",
            file=sys.stderr,
        )
        return {}


def site_path_prefix() -> str:
    with HUGO_TOML.open("rb") as fp:
        cfg = tomllib.load(fp)
    base = cfg.get("baseURL", "/")
    m = re.match(r"^[a-z]+://[^/]+(/.*)?$", base)
    prefix = (m.group(1) if m and m.group(1) else "/") if m else base
    if not prefix.endswith("/"):
        prefix += "/"
    return prefix


def collect_wiki(prefix: str) -> list[dict]:
    if not WIKI_DIR.is_dir():
        return []
    entries: list[dict] = []
    for md in sorted(WIKI_DIR.rglob("*.md")):
        if md.name == "_index.md":
            continue
        fm = parse_frontmatter(md)
        title = (fm.get("title") or "").strip()
        aliases = fm.get("aliases") or []
        description = (fm.get("description") or "").strip()
        rel = md.relative_to(WIKI_DIR)
        if len(rel.parts) < 2:
            continue
        section = rel.parts[0]
        slug = md.stem
        url = f"{prefix}wiki/{section}/{slug}/"
        target_id = f"wiki:{section}/{slug}"
        keywords: list[str] = []
        if title:
            keywords.append(title)
        for a in aliases:
            if not a:
                continue
            a = str(a).strip()
            if a and a not in keywords:
                keywords.append(a)
        for kw in keywords:
            if not keyword_passes(kw):
                continue
            entries.append(
                {
                    "keyword": kw,
                    "url": url,
                    "type": "wiki",
                    "source": "title" if kw == title else "alias",
                    "section": section,
                    "description": description,
                    "target_id": target_id,
                }
            )
    return entries


def collect_tags(prefix: str) -> list[dict]:
    tags_dir = PUBLIC_DIR / "tags"
    if not tags_dir.is_dir():
        print("warn: public/tags/ not found; run `hugo --gc` first", file=sys.stderr)
        return []
    entries: list[dict] = []
    for tag_dir in sorted(tags_dir.iterdir()):
        if not tag_dir.is_dir():
            continue
        idx = tag_dir / "index.html"
        if not idx.exists():
            continue
        html = idx.read_text(encoding="utf-8", errors="ignore")
        m = TAG_TITLE_RE.search(html)
        if m:
            display = HTML_TAG_RE.sub("", m.group(1)).strip()
        else:
            display = tag_dir.name
        if not keyword_passes(display):
            continue
        url = f"{prefix}tags/{tag_dir.name}/"
        entries.append(
            {
                "keyword": display,
                "url": url,
                "type": "tag",
                "source": "title",
                "description": f"タグ: {display}",
                "target_id": f"tag:{tag_dir.name}",
            }
        )
    return entries


def deduplicate(entries: list[dict]) -> list[dict]:
    """When the same surface keyword maps to multiple targets, pick deterministically."""
    type_order = {"wiki": 0, "tag": 1}
    source_order = {"title": 0, "alias": 1}
    section_order = {"concepts": 0, "tools": 1, "guides": 2, "qa": 3}

    def rank(e: dict) -> tuple:
        return (
            type_order.get(e.get("type"), 99),
            source_order.get(e.get("source"), 99),
            section_order.get(e.get("section"), 99),
            e.get("target_id", ""),
        )

    by_cf: dict[str, dict] = {}
    for e in entries:
        cf = e["keyword"].casefold()
        if not cf:
            continue
        existing = by_cf.get(cf)
        if existing is None:
            by_cf[cf] = e
        elif e.get("target_id") == existing.get("target_id"):
            continue
        elif rank(e) < rank(existing):
            print(
                "warn: keyword collision: "
                f"{e['keyword']!r} kept {e['target_id']} over {existing['target_id']}",
                file=sys.stderr,
            )
            by_cf[cf] = e
        else:
            print(
                "warn: keyword collision: "
                f"{e['keyword']!r} kept {existing['target_id']} over {e['target_id']}",
                file=sys.stderr,
            )
    return sorted(by_cf.values(), key=lambda x: (-len(x["keyword"]), x["keyword"]))


def main() -> None:
    prefix = site_path_prefix()
    wiki = collect_wiki(prefix)
    tags = collect_tags(prefix)
    merged = deduplicate(wiki + tags)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(
        json.dumps(merged, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    n_wiki = sum(1 for e in merged if e["type"] == "wiki")
    n_tag = sum(1 for e in merged if e["type"] == "tag")
    print(
        f"wrote {len(merged)} entries → {OUT_PATH.relative_to(ROOT)}", file=sys.stderr
    )
    print(f"  wiki: {n_wiki}  tag: {n_tag}  prefix: {prefix}", file=sys.stderr)


if __name__ == "__main__":
    main()
